### ISSUE TITLE
Improve clan description storage

### ISSUE THREAD

**Issue by RobinZergiebel** [oraum/VTMsite#22]
@oraum Can we somehow import the clan descriptions from the wiki? If no, maybe we should consider a database?

**Comment by RobinZergiebel** [comment]
Just found this: https://www.reddit.com/r/learnpython/comments/n8al5o/fandom_wiki_api/.

Probably not a good idea to scrape the wiki...

**Comment by oraum** [comment]
I don't think scraping might be a valid solution. A database might be a possibility but I would prefer something simple like a dedicated json file. Are there any plans for internationalization? So do we need to store a german/... description as well?

**Comment by RobinZergiebel** [comment]
A json file sounds like a good idea. German translations would be nice, but are not really a priority atm.

**Comment by RobinZergiebel** [comment]
Maintaining clan descriptions requires a lot of effort and could lead to some copyright issues. Doesn't seem worth it and I guess the chance that someone picks a clan without knowing anything about the clan is pretty slim. Closed.
